services:
  mysql-primary:
    image: mysql:8.0.39
    container_name: mysql-primary
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row --gtid-mode=ON --enforce-gtid-consistency=ON
    # volumes:
    #   - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: opensesame
      MYSQL_DATABASE: test
      MYSQL_USER: repl
      MYSQL_PASSWORD: repl
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - '3307'
  mysql-replica:
    image: mysql:8.0.39
    container_name: mysql-replica
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row --gtid-mode=ON --enforce-gtid-consistency=ON
    # volumes:
    #   - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: opensesame
      MYSQL_DATABASE: test
      MYSQL_USER: repl
      MYSQL_PASSWORD: repl
      MYSQL_TCP_PORT: 3308
    ports:
      - '3308:3308'
    expose:
      - '3308'
